trigger:
- development
- master

pr:
- development
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: buildConfiguration
    value: 'Release'
  - name: dotnetVersion
    value: '3.1.x'
  - name: MSBUILDSINGLELOADCONTEXT
    value: '1'
  - name: BROWSER
    value: chrome
  - name: BAPIDB__SERVERURL
    value: $(SERVERURL)
  - name: BAPIDB__DATABASENAME
    value: bc-buyingcatalogue-development-helm-bapi
  - name: ISAPIDB__SERVERURL
    value: $(SERVERURL)
  - name: ISAPIDB__DATABASENAME
    value: bc-buyingcatalogue-development-helm-isapi
  - name: ORDAPIDB__SERVERURL
    value: $(SERVERURL)
  - name: ORDAPIDB__DATABASENAME
    value: bc-buyingcatalogue-development-helm-ordapi
  - group: dev-secrets

steps:
- task: UseGitVersion@5
  name: gitversion
  displayName: Work out version
  inputs:
    versionSpec: '5.x'

- task: UseDotNet@2
  displayName: 'Use DotNet Core $(dotnetVersion)'
  inputs:
    version: $(dotnetVersion)
    includePreviewVersions: false

- bash: |
    echo "##vso[task.setvariable variable=PBHOSTURL]$(echo "${PBURL##*://}")"  
  displayName: Set up Host URL

- bash: |
    echo "51.11.46.27    $PBHOSTURL" | sudo tee -a /etc/hosts
    curl -k -i $(PBURL) --fail --connect-timeout 30
  displayName: 'Check URL is reachable'

- bash: |
    chmod +x ./selenium-grid-setup.sh
    ./selenium-grid-setup.sh
    if [ $? -ne 0 ]; then exit 1; fi
  displayName: Selenium Grid Setup

- bash: |
    export BAPIDB__PASSWORD="$(gpitfuturesdevdbpassword)" 
    export ISAPIDB__PASSWORD="$(gpitfuturesdevdbpassword)"
    export ORDAPIDB__PASSWORD="$(gpitfuturesdevdbpassword)"
    echo $(BAPIDB__PASSWORD) $(BAPIDB__SERVERURL) $(BAPIDB__DATABASENAME)

    dotnet test src/ -v n
  displayName: Run All Acceptance Tests
  
- task: Docker@2
  condition: and(always(), or(eq(variables['Build.SourceBranch'], 'refs/heads/development'),eq(variables['Build.SourceBranch'], 'refs/heads/master')))
  displayName: Build and push docker image
  inputs:
    containerRegistry: 'gpitfuturesdevacr'
    repository: 'nhsd/buying-catalogue/of-ac-tests'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: "$(GitVersion.SemVer)"
    addPipelineData: false

- task: HelmInstaller@1
  displayName: 'Install helm'
  condition: and(always(), or(eq(variables['Build.SourceBranch'], 'refs/heads/development'),eq(variables['Build.SourceBranch'], 'refs/heads/master')))
  inputs:
    helmVersionToInstall: 'latest'

- bash: |
    cd charts
    helm package \
        --version $(GitVersion.SemVer) \
        --app-version $(GitVersion.SemVer) \
        of-ac-tests
  failOnStderr: true
  condition: and(always(), or(eq(variables['Build.SourceBranch'], 'refs/heads/development'),eq(variables['Build.SourceBranch'], 'refs/heads/master')))
  name: helmPackage
  displayName: 'Helm package'

- bash: |
    cd charts
    chartPackage=$(ls of-ac-tests-*.tgz)
    az acr helm push --force \
        -n "gpitfuturesdevacr" \
        -u "gpitfuturesdevacr" \
        -p $(gpitfuturesdevacr-pass) \
        $chartPackage
  failOnStderr: false
  condition: and(always(), or(eq(variables['Build.SourceBranch'], 'refs/heads/development'),eq(variables['Build.SourceBranch'], 'refs/heads/master')))
  name: helmPush
  displayName: 'Push helm chart to acr'



